name: universal_todo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  flex_color_scheme: ^4.2.0
  cupertino_icons: ^1.0.2
  get_it: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.0


flutter:
  #  generate: true
  uses-material-design: true

  assets:
    - assets/images/

